# Generated by Django 4.2.7 on 2023-12-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/doctor_profile_images/"
            ),
        ),
    ]
