# Generated by Django 4.2.7 on 2023-12-18 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare", "0002_alter_doctor_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="profile_image",
        ),
    ]
