# Generated by Django 4.2.7 on 2023-12-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare", "0003_remove_doctor_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="image_filename",
            field=models.CharField(default="d1.jpg", max_length=255),
        ),
    ]
